version: '3.7'

services:
  web:
    build:
      context: ./app
    restart: unless-stopped
    volumes:
      - ./app/:/usr/src/app/
      - ./data/app_data:/data
      - ./data/static_volume:/home/app/web/static
    tty: true
    ports:
      - $PORT:8000
    env_file:
      - ./.env
